#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${AGENTS_REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
DEST="${HOME}/.claude"
BACKUP_DIR="${DEST}/backups"
AGENTS_DEST="${HOME}/.agents"
CODEX_DEST="${HOME}/.codex"

# Line 1 of a file we generated. Its absence means the file is yours.
GEN_MARKER="<!-- generated by jahnkelabs/agents scripts/install.sh -- do not edit -->"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'USAGE'
Usage: install.sh [--rules-only]

Installs this repository for both runtimes.

Claude reads directories of rules, output styles, and skills, so each one
links per entry:

  ~/.claude/rules/<name>.md         -> rules/<name>.md          (per file)
  ~/.claude/output-styles/<name>.md -> output-styles/<name>.md   (per file)
  ~/.claude/skills/<name>           -> skills/<name>/            (per skill)
  ~/.claude/references              -> references/               (whole directory)

Codex reads skills from ~/.agents/skills and follows symlinks, so those link
the same way. It reads instructions from a single file with no include
mechanism, so the rules and the output styles are concatenated instead of
linked:

  ~/.agents/skills/<name>       -> skills/<name>/         (per skill)
  ~/.agents/references          -> references/            (whole directory)
  ~/.codex/AGENTS.md             = rules/*.md + output-styles/*.md (generated)

Rules and skills are linked one at a time, so the directories stay real ones
you own. Anything else you keep there is left alone, and nothing you create
locally lands in this repo.

The /worktree clone helper links to a stable path, so a per-repository
provisioning script can call it without knowing where this repo lives:

  ~/.claude/bin/wt-clone.sh     -> scripts/wt-clone.sh

The install also sets "outputStyle": "prose-discipline" in
~/.claude/settings.json. That key selects the prose style for every Claude
session. An outputStyle you set yourself is left alone, and the step is
skipped when jq is absent.

Re-run after adding or renaming a file. The per-entry links -- rules, output
styles, and skills -- are pruned once their source has gone, and nothing else
is touched. The two direct links, references/ and bin/wt-clone.sh, are not
pruned, so renaming either source leaves the old link dangling.

A generated ~/.codex/AGENTS.md is the one file this repository writes rather
than links, because Codex gives it no other shape. An existing file that we
did not generate is backed up first. Git hooks in this repository regenerate
it after a commit, checkout, or merge, so an edit you commit takes effect
without a re-run. --rules-only does just that regeneration, and the hooks
call it.

The install writes those hooks only when AGENTS_REPO is the root of a git
repository. It writes them where core.hooksPath points, because that is where
git reads them. It names the directory it wrote, and it says so when it skips.

Override the repo root with AGENTS_REPO=/path/to/agents.
USAGE
  exit 0
fi

# Symlink source -> dest, preserving anything real that is already there.
link() {
  local source="$1" dest="$2"

  if [[ ! -e "${source}" ]]; then
    echo "error: source missing: ${source}" >&2
    exit 1
  fi

  local shown="${dest#"${HOME}/"}"

  if [[ -L "${dest}" ]]; then
    local current
    current="$(readlink "${dest}")"
    if [[ "${current}" == "${source}" ]]; then
      echo "  already linked: ${shown}"
      return
    fi
    echo "  repointing: ${shown} (was ${current})"
    rm -f "${dest}"
  elif [[ -e "${dest}" ]]; then
    mkdir -p "${BACKUP_DIR}"
    local backup
    backup="${BACKUP_DIR}/$(basename "${dest}").$(date +%s)"
    mv "${dest}" "${backup}"
    echo "  backed up: ${shown} -> backups/$(basename "${backup}")"
  fi

  ln -sfn "${source}" "${dest}"
  echo "  linked: ${shown}"
}

# Link each entry of src_dir individually into dest_dir, then prune our own
# stale links. Entries we did not create are never touched.
#   $1 = directory name under both the repo and the destination root
#   $2 = "files" to link *.md, or "dirs" to link each subdirectory
#   $3 = destination root, defaulting to ~/.claude
link_entries() {
  local kind="$2"
  local dest_root="${3:-${DEST}}"
  local src_dir="${REPO_ROOT}/$1" dest_dir="${dest_root}/$1"

  if [[ ! -d "${src_dir}" ]]; then
    echo "error: source directory missing: ${src_dir}" >&2
    exit 1
  fi

  # An earlier version linked the whole directory. Replace that with a real
  # one -- removing the symlink does not touch the repo it points at.
  if [[ -L "${dest_dir}" ]]; then
    echo "  converting ${1}/ from a directory link to a real directory"
    rm -f "${dest_dir}"
  elif [[ -e "${dest_dir}" && ! -d "${dest_dir}" ]]; then
    mkdir -p "${BACKUP_DIR}"
    mv "${dest_dir}" "${BACKUP_DIR}/$(basename "${dest_dir}").$(date +%s)"
    echo "  backed up a file blocking ${1}/"
  fi
  mkdir -p "${dest_dir}"

  shopt -s nullglob

  if [[ "${kind}" == "dirs" ]]; then
    for src in "${src_dir}"/*/; do
      src="${src%/}"
      link "${src}" "${dest_dir}/$(basename "${src}")"
    done
  else
    for src in "${src_dir}"/*.md; do
      link "${src}" "${dest_dir}/$(basename "${src}")"
    done
  fi

  # Prune links into this repo whose source is gone (renamed or deleted).
  # Only symlinks resolving under src_dir qualify -- your own files and links
  # elsewhere are left exactly as they are.
  for dest in "${dest_dir}"/* "${dest_dir}"/.*; do
    [[ -L "${dest}" ]] || continue
    local target
    target="$(readlink "${dest}")"
    [[ "${target}" == "${src_dir}/"* ]] || continue
    if [[ ! -e "${target}" ]]; then
      rm -f "${dest}"
      echo "  pruned: ${1}/$(basename "${dest}") (source removed)"
    fi
  done

  shopt -u nullglob
}

# Codex reads one instructions file and resolves no includes, so the rules and
# the output styles are concatenated rather than linked. Frontmatter is
# stripped: Codex has no use for it, and a stray --- fence renders as a
# horizontal rule.
generate_codex_rules() {
  local out="${CODEX_DEST}/AGENTS.md"
  mkdir -p "${CODEX_DEST}"

  if [[ -e "${out}" ]] && ! head -n 1 "${out}" | grep -qF "${GEN_MARKER}"; then
    mkdir -p "${BACKUP_DIR}"
    mv "${out}" "${BACKUP_DIR}/AGENTS.md.$(date +%s)"
    echo "  backed up your ~/.codex/AGENTS.md -> backups/"
  fi

  {
    echo "${GEN_MARKER}"
    echo "<!-- source: ${REPO_ROOT}/{rules,output-styles} -- regenerate with scripts/install.sh -->"
    echo ""
    shopt -s nullglob
    for src in "${REPO_ROOT}"/rules/*.md "${REPO_ROOT}"/output-styles/*.md; do
      awk 'NR==1 && /^---$/ {fm=1; next} fm && /^---$/ {fm=0; next} !fm' "${src}"
      echo ""
    done
    shopt -u nullglob
  } > "${out}"

  echo "  generated: .codex/AGENTS.md ($(wc -l < "${out}" | tr -d ' ') lines)"
}

# Claude reads the selected style from settings.json, which is yours to own, so
# a value you already set is kept rather than replaced.
select_output_style() {
  local f="${DEST}/settings.json"

  if ! command -v jq >/dev/null 2>&1; then
    echo "  jq not found -- cannot select the output style"
    echo "  run /config and pick prose-discipline, or add"
    echo '  "outputStyle": "prose-discipline" to settings.json'
    return
  fi

  if [[ ! -f "${f}" ]] && ! echo '{}' > "${f}" 2>/dev/null; then
    echo "  cannot create settings.json -- skipping the output style"
    echo "  pick prose-discipline in /config instead"
    return
  fi

  if ! jq -e 'type == "object"' "${f}" >/dev/null 2>&1; then
    echo "  settings.json is not a JSON object -- skipping the output style"
    echo "  fix it and re-run, or pick prose-discipline in /config"
    return
  fi

  local current
  current="$(jq -r '.outputStyle // ""' "${f}")"

  if [[ "${current}" == "prose-discipline" ]]; then
    echo "  already selected: outputStyle"
    return
  fi

  if [[ -n "${current}" ]]; then
    echo "  kept your outputStyle=${current}"
    echo "  -- set it to prose-discipline in /config"
    return
  fi

  local tmp
  if ! tmp="$(mktemp "${f}.XXXXXX")"; then
    echo "  cannot write in ${DEST} -- skipping the output style"
    return
  fi

  # cat rather than mv: it writes through a symlink and keeps the mode and owner.
  if jq '. + {outputStyle: "prose-discipline"}' "${f}" > "${tmp}" \
     && cat "${tmp}" > "${f}"; then
    rm -f "${tmp}"
    echo "  selected: outputStyle=prose-discipline"
    echo "  (start a new claude session to load it)"
  else
    rm -f "${tmp}"
    echo "  could not write settings.json -- pick prose-discipline in /config"
  fi
}

# Regenerate after the tree changes, so a committed rule edit reaches Codex
# without a re-run. Only hooks we wrote are replaced; yours are left alone.
install_git_hooks() {
  local toplevel root_real top_real hooks
  if ! toplevel="$(git -C "${REPO_ROOT}" rev-parse --show-toplevel 2>/dev/null)" \
     || [[ -z "${toplevel}" ]]; then
    echo "  no git repository at ${REPO_ROOT} -- skipped the hooks"
    return 0
  fi

  root_real="$(cd -P "${REPO_ROOT}" 2>/dev/null && pwd -P)" || return 0
  top_real="$(cd -P "${toplevel}" 2>/dev/null && pwd -P)" || return 0
  if [[ "${root_real}" != "${top_real}" ]]; then
    echo "  ${REPO_ROOT} is not the root of a git repository -- skipped the hooks"
    echo "  it sits inside ${top_real}, whose hooks are not ours to write"
    return 0
  fi

  if ! hooks="$(git -C "${REPO_ROOT}" rev-parse --path-format=absolute --git-path hooks 2>/dev/null)" \
     || [[ -z "${hooks}" ]]; then
    echo "  git could not resolve the hooks directory -- skipped the hooks"
    return 0
  fi

  if ! mkdir -p "${hooks}"; then
    echo "  cannot create ${hooks} -- skipped the hooks"
    return 0
  fi

  local hook
  for hook in post-commit post-checkout post-merge; do
    local path="${hooks}/${hook}"
    if [[ -L "${path}" ]] \
       || { [[ -e "${path}" ]] && ! grep -qF "${GEN_MARKER}" "${path}" 2>/dev/null; }; then
      echo "  kept your ${hook} hook -- add scripts/install.sh --rules-only to it"
      continue
    fi
    cat > "${path}" <<HOOK
#!/usr/bin/env bash
# ${GEN_MARKER}
exec "${REPO_ROOT}/scripts/install.sh" --rules-only >/dev/null
HOOK
    chmod +x "${path}"
  done
  echo "  installed git hooks in ${hooks}: post-commit, post-checkout, post-merge"
}

if [[ "${1:-}" == "--rules-only" ]]; then
  generate_codex_rules
  exit 0
fi

mkdir -p "${DEST}"

echo "Installing for Claude..."
link_entries rules files
link_entries output-styles files
select_output_style
link_entries skills dirs
link "${REPO_ROOT}/references" "${DEST}/references"
if [[ -L "${DEST}/bin" || ( -e "${DEST}/bin" && ! -d "${DEST}/bin" ) ]]; then
  mkdir -p "${BACKUP_DIR}"
  mv "${DEST}/bin" "${BACKUP_DIR}/bin.$(date +%s)"
  echo "  backed up something blocking bin/ -> backups/"
fi
mkdir -p "${DEST}/bin"
link "${REPO_ROOT}/scripts/wt-clone.sh" "${DEST}/bin/wt-clone.sh"

echo "Installing for Codex..."
mkdir -p "${AGENTS_DEST}"
link_entries skills dirs "${AGENTS_DEST}"
link "${REPO_ROOT}/references" "${AGENTS_DEST}/references"
generate_codex_rules
install_git_hooks

# Earlier versions installed these as commands. A skill and a command of the
# same name both resolve to /name, and the skill wins -- so a leftover link
# is shadowed rather than broken, but it is still stale. Remove ours only.
if [[ -d "${DEST}/commands" && ! -L "${DEST}/commands" ]]; then
  shopt -s nullglob
  for old in "${DEST}"/commands/*.md; do
    [[ -L "${old}" ]] || continue
    target="$(readlink "${old}")"
    [[ "${target}" == "${REPO_ROOT}/commands/"* ]] || continue
    rm -f "${old}"
    echo "  removed superseded command link: commands/$(basename "${old}")"
  done
  shopt -u nullglob
  rmdir "${DEST}/commands" 2>/dev/null && echo "  removed empty commands/"
elif [[ -L "${DEST}/commands" ]] && [[ "$(readlink "${DEST}/commands")" == "${REPO_ROOT}/commands" ]]; then
  rm -f "${DEST}/commands"
  echo "  removed superseded commands/ directory link"
fi

echo ""
echo "Installed for both runtimes. Rules apply to every session; skills are"
echo "slash commands on Claude and \$-invoked skills on Codex."
echo "Claude's prose style lives in the outputStyle key of"
echo "your ~/.claude/settings.json. Start a new claude session to load it."
echo "/research, /plan, /implement, /critique, /retro, /worktree, /stash and /recall"
echo "require the Solo MCP server."
echo "/stash and /recall additionally require a tracker MCP (see references/)."
echo ""
echo "Codex has no disable-model-invocation, so it can invoke /plan, /implement,"
echo "/bare-convert, /stash and /recall itself. Their approval gates still hold."
