#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${AGENTS_REPO:-$(cd "$(dirname "$0")/.." && pwd)}"
DEST="${HOME}/.claude"
BACKUP_DIR="${DEST}/backups"
AGENTS_DEST="${HOME}/.agents"
CODEX_DEST="${HOME}/.codex"

# Line 1 of a file we generated. Its absence means the file is yours.
GEN_MARKER="<!-- generated by jahnkelabs/agents scripts/install.sh -- do not edit -->"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'USAGE'
Usage: install.sh [--rules-only]

Installs this repository for both runtimes.

Claude reads a directory of rules and a directory of skills, so both link
per entry:

  ~/.claude/rules/<name>.md     -> rules/<name>.md        (per file)
  ~/.claude/skills/<name>       -> skills/<name>/         (per skill)
  ~/.claude/references          -> references/            (whole directory)

Codex reads skills from ~/.agents/skills and follows symlinks, so those link
the same way. It reads instructions from a single file with no include
mechanism, so the rules are concatenated instead of linked:

  ~/.agents/skills/<name>       -> skills/<name>/         (per skill)
  ~/.agents/references          -> references/            (whole directory)
  ~/.codex/AGENTS.md             = rules/*.md concatenated   (generated)

Rules and skills are linked one at a time, so the directories stay real ones
you own. Anything else you keep there is left alone, and nothing you create
locally lands in this repo.

Re-run after adding or renaming a file. Links pointing into this repo whose
source has gone are pruned; nothing else is touched.

A generated ~/.codex/AGENTS.md is the one file this repository writes rather
than links, because Codex gives it no other shape. An existing file that we
did not generate is backed up first. Git hooks in this repository regenerate
it after a commit, checkout, or merge, so an edit you commit takes effect
without a re-run. --rules-only does just that regeneration, and the hooks
call it.

Override the repo root with AGENTS_REPO=/path/to/agents.
USAGE
  exit 0
fi

# Symlink source -> dest, preserving anything real that is already there.
link() {
  local source="$1" dest="$2"

  if [[ ! -e "${source}" ]]; then
    echo "error: source missing: ${source}" >&2
    exit 1
  fi

  local shown="${dest#"${HOME}/"}"

  if [[ -L "${dest}" ]]; then
    local current
    current="$(readlink "${dest}")"
    if [[ "${current}" == "${source}" ]]; then
      echo "  already linked: ${shown}"
      return
    fi
    echo "  repointing: ${shown} (was ${current})"
    rm -f "${dest}"
  elif [[ -e "${dest}" ]]; then
    mkdir -p "${BACKUP_DIR}"
    local backup
    backup="${BACKUP_DIR}/$(basename "${dest}").$(date +%s)"
    mv "${dest}" "${backup}"
    echo "  backed up: ${shown} -> backups/$(basename "${backup}")"
  fi

  ln -sfn "${source}" "${dest}"
  echo "  linked: ${shown}"
}

# Link each entry of src_dir individually into dest_dir, then prune our own
# stale links. Entries we did not create are never touched.
#   $1 = directory name under both the repo and the destination root
#   $2 = "files" to link *.md, or "dirs" to link each subdirectory
#   $3 = destination root, defaulting to ~/.claude
link_entries() {
  local kind="$2"
  local dest_root="${3:-${DEST}}"
  local src_dir="${REPO_ROOT}/$1" dest_dir="${dest_root}/$1"

  if [[ ! -d "${src_dir}" ]]; then
    echo "error: source directory missing: ${src_dir}" >&2
    exit 1
  fi

  # An earlier version linked the whole directory. Replace that with a real
  # one -- removing the symlink does not touch the repo it points at.
  if [[ -L "${dest_dir}" ]]; then
    echo "  converting ${1}/ from a directory link to a real directory"
    rm -f "${dest_dir}"
  elif [[ -e "${dest_dir}" && ! -d "${dest_dir}" ]]; then
    mkdir -p "${BACKUP_DIR}"
    mv "${dest_dir}" "${BACKUP_DIR}/$(basename "${dest_dir}").$(date +%s)"
    echo "  backed up a file blocking ${1}/"
  fi
  mkdir -p "${dest_dir}"

  shopt -s nullglob

  if [[ "${kind}" == "dirs" ]]; then
    for src in "${src_dir}"/*/; do
      src="${src%/}"
      link "${src}" "${dest_dir}/$(basename "${src}")"
    done
  else
    for src in "${src_dir}"/*.md; do
      link "${src}" "${dest_dir}/$(basename "${src}")"
    done
  fi

  # Prune links into this repo whose source is gone (renamed or deleted).
  # Only symlinks resolving under src_dir qualify -- your own files and links
  # elsewhere are left exactly as they are.
  for dest in "${dest_dir}"/* "${dest_dir}"/.*; do
    [[ -L "${dest}" ]] || continue
    local target
    target="$(readlink "${dest}")"
    [[ "${target}" == "${src_dir}/"* ]] || continue
    if [[ ! -e "${target}" ]]; then
      rm -f "${dest}"
      echo "  pruned: ${1}/$(basename "${dest}") (source removed)"
    fi
  done

  shopt -u nullglob
}

# Codex reads one instructions file and resolves no includes, so the rules are
# concatenated rather than linked. Frontmatter is stripped: Codex has no use for
# it, and a stray --- fence renders as a horizontal rule.
generate_codex_rules() {
  local out="${CODEX_DEST}/AGENTS.md"
  mkdir -p "${CODEX_DEST}"

  if [[ -e "${out}" ]] && ! head -n 1 "${out}" | grep -qF "${GEN_MARKER}"; then
    mkdir -p "${BACKUP_DIR}"
    mv "${out}" "${BACKUP_DIR}/AGENTS.md.$(date +%s)"
    echo "  backed up your ~/.codex/AGENTS.md -> backups/"
  fi

  {
    echo "${GEN_MARKER}"
    echo "<!-- source: ${REPO_ROOT}/rules -- regenerate with scripts/install.sh -->"
    echo ""
    shopt -s nullglob
    for src in "${REPO_ROOT}"/rules/*.md; do
      awk 'NR==1 && /^---$/ {fm=1; next} fm && /^---$/ {fm=0; next} !fm' "${src}"
      echo ""
    done
    shopt -u nullglob
  } > "${out}"

  echo "  generated: .codex/AGENTS.md ($(wc -l < "${out}" | tr -d ' ') lines)"
}

# Regenerate after the tree changes, so a committed rule edit reaches Codex
# without a re-run. Only hooks we wrote are replaced; yours are left alone.
install_git_hooks() {
  local hooks="${REPO_ROOT}/.git/hooks"
  [[ -d "${hooks}" ]] || return 0

  local hook
  for hook in post-commit post-checkout post-merge; do
    local path="${hooks}/${hook}"
    if [[ -e "${path}" ]] && ! grep -qF "${GEN_MARKER}" "${path}" 2>/dev/null; then
      echo "  kept your ${hook} hook -- add scripts/install.sh --rules-only to it"
      continue
    fi
    cat > "${path}" <<HOOK
#!/usr/bin/env bash
# ${GEN_MARKER}
exec "${REPO_ROOT}/scripts/install.sh" --rules-only >/dev/null
HOOK
    chmod +x "${path}"
  done
  echo "  installed git hooks: post-commit, post-checkout, post-merge"
}

if [[ "${1:-}" == "--rules-only" ]]; then
  generate_codex_rules
  exit 0
fi

mkdir -p "${DEST}"

echo "Installing for Claude..."
link_entries rules files
link_entries skills dirs
link "${REPO_ROOT}/references" "${DEST}/references"

echo "Installing for Codex..."
mkdir -p "${AGENTS_DEST}"
link_entries skills dirs "${AGENTS_DEST}"
link "${REPO_ROOT}/references" "${AGENTS_DEST}/references"
generate_codex_rules
install_git_hooks

# Earlier versions installed these as commands. A skill and a command of the
# same name both resolve to /name, and the skill wins -- so a leftover link
# is shadowed rather than broken, but it is still stale. Remove ours only.
if [[ -d "${DEST}/commands" && ! -L "${DEST}/commands" ]]; then
  shopt -s nullglob
  for old in "${DEST}"/commands/*.md; do
    [[ -L "${old}" ]] || continue
    target="$(readlink "${old}")"
    [[ "${target}" == "${REPO_ROOT}/commands/"* ]] || continue
    rm -f "${old}"
    echo "  removed superseded command link: commands/$(basename "${old}")"
  done
  shopt -u nullglob
  rmdir "${DEST}/commands" 2>/dev/null && echo "  removed empty commands/"
elif [[ -L "${DEST}/commands" ]] && [[ "$(readlink "${DEST}/commands")" == "${REPO_ROOT}/commands" ]]; then
  rm -f "${DEST}/commands"
  echo "  removed superseded commands/ directory link"
fi

echo ""
echo "Installed for both runtimes. Rules apply to every session; skills are"
echo "slash commands on Claude and \$-invoked skills on Codex."
echo "/plan, /implement, /critique, /stash and /recall require the Solo MCP server."
echo "/stash and /recall additionally require a tracker MCP (see references/)."
echo ""
echo "Codex has no disable-model-invocation, so it can invoke /plan, /implement,"
echo "/stash and /recall itself. Their approval gates still hold."
